# LA CAMPEONA PTACARRETAS #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacampeonaptacarretas-deployment
  namespace: tiendas-rhino
  labels:
    app: lacampeonaptacarretas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lacampeonaptacarretas
  template:
    metadata:
      labels:
        app: lacampeonaptacarretas
    spec:
      containers:
      - name: lacampeonaptacarretas
        image: southamerica-east1-docker.pkg.dev/diesel-talon-387022/tienda-rhino/tienda-rhino:66262eaf4fbf76a27b5fe607a27eb669f88b9803
        imagePullPolicy: Always
        env:
          - name: ESTILO_PRODUCTOS
            value: image_min
          - name: NEXT_PUBLIC_SUCURSAL_ID
            value: "138"
          - name: NEXT_PUBLIC_API_TIENDA_ENDPOINT
            value: "http://apitiendadev.rhinox.io/v1/tienda"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
# LA CAMPEONA CORDON #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacampeonacordon-deployment
  namespace: tiendas-rhino
  labels:
    app: lacampeonacordon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lacampeonacordon
  template:
    metadata:
      labels:
        app: lacampeonacordon
    spec:
      containers:
      - name: lacampeonacordon
        image: southamerica-east1-docker.pkg.dev/diesel-talon-387022/tienda-rhino/tienda-rhino:66262eaf4fbf76a27b5fe607a27eb669f88b9803
        imagePullPolicy: Always
        env:
          - name: ESTILO_PRODUCTOS
            value: image_full
          - name: NEXT_PUBLIC_SUCURSAL_ID
            value: "137"
          - name: NEXT_PUBLIC_API_TIENDA_ENDPOINT
            value: "http://apitiendadev.rhinox.io/v1/tienda"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80